### PR TITLE
Fix multiple overflow errors

### LINKED ISSUE #4: integer overflow causes panic
A version number like "18446744073709551616.0.0" will pass the regex but fail to parse as a u64, causing `version::parse` to panic in one of the `unwrap` calls (rather than returning an error).

### PR DESCRIPTION
**Pull request by ScottAbbey**
Recently merged #10 helped handle overflow on the major version number, but didn't address overflow for the minor, patch, and meta version numbers.

Overflow on minor and patch versions currently causes them to be regarded as wildcards, so comparing very large minor or patch versions would mysteriously not work.

Prerelease numeric identifiers with overflow currently cause cargo to panic with an Overflow error. One potential place where this could happen is if someone tried adding a YmdHMSN timestamp (like `20170124231042736784549`) to their prerelease tag.  I'm not sure how I feel about calling a number AlphaNumeric when it is actually Numeric, but it seems better than crashing.

I am new to Rust, so please help me correct any unidiomatic usage.

### CODE REVIEW

File: src/common.rs [hunk 1]
```diff
@@ -17,8 +17,11 @@ pub fn parse_meta(s: &str) -> Vec<Identifier> {
             if is_alpha_numeric(part) {
                 Identifier::AlphaNumeric(part.to_string())
             } else {
-                // we can unwrap here because we know it is only digits due to the regex
-                Identifier::Numeric(part.parse().unwrap())
+                // if the number is too large to fit in Numeric, treat it as a string
```
Comment (steveklabnik) [inline src/common.rs]: yeah, this is very interesting. i'm going to give this some thought.

**Review by steveklabnik — COMMENTED** [review]
Thanks for this! Your rust is great. I'm also not sure about this approach; let me think about it.

**Comment by ScottAbbey** [comment]
I backed out the questionable changes to `parse_meta` leaving only the fixes for minor and patch version overflow handling.  Let me know if you have any issues with the current pull request or suggestions on an appropriate way to handle overflow in a prerelease numeric identifier.

**Comment by steveklabnik** [comment]
Sorry this review is taking me a few days! I'll try to get to it soon.

**Comment by steveklabnik** [comment]
Looks good, thank you!
